version: '3.1'

services:
  mongo:
    image: mongo:3.6
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mynetwork
    expose:
      - 27017
    ports:
      - 30002:27017
  nestjs-auth:
    container_name: 'nest_auth'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    restart: always
    ports:
      - 3000:3000
    networks:
      - mynetwork
    depends_on:
      - mongo

volumes:
  mongodata:

networks:
  mynetwork:
